# Generated by Django 5.0.4 on 2024-05-04 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('security_control', 'Security Control'), ('wc', 'WC'), ('boarding_door', 'Boarding Door')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BoardingDoor',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Location.location')),
                ('code', models.CharField(max_length=100)),
                ('finger', models.BooleanField(default=False)),
            ],
            bases=('Location.location',),
        ),
    ]
