# Generated by Django 5.0.4 on 2024-05-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0001_initial'),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boarding',
            fields=[
                ('boarding_door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Location.boardingdoor')),
                ('opening_time', models.TimeField()),
                ('last_call', models.TimeField()),
                ('opened', models.BooleanField(default=False)),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Flight.flight')),
            ],
        ),
    ]
