# Generated by Django 5.0.4 on 2024-05-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('visual_percentage', models.IntegerField()),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('pwd', models.CharField(max_length=255, unique=True)),
                ('DNI', models.CharField(max_length=255, unique=True)),
                ('passport', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
