# Generated by Django 5.0.4 on 2024-05-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_address_alter_user_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='DNI',
            new_name='dni',
        ),
    ]
