# Generated by Django 5.0.4 on 2024-05-04 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0001_initial'),
        ('User', '0003_rename_dni_user_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_flight',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='Flight.flight'),
            preserve_default=False,
        ),
    ]
