# Generated by Django 5.0.4 on 2024-05-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_user_assigned_flight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_flight',
        ),
    ]
