# Generated by Django 5.0.4 on 2024-05-04 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0002_boarding'),
        ('User', '0018_user_assigned_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Flight.flight')),
                ('seat', models.CharField(max_length=255)),
                ('fast_track', models.BooleanField(default=False)),
                ('priority', models.BooleanField(default=False)),
                ('bags', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
